### ISSUE TITLE
REST Patterns

### ISSUE THREAD

**Issue by lsilva-kununu** [kamilmysliwiec/nest#122]
I think is a great idea to remove responses inside controllers and use REST patterns to manage response status code, for example, POST should return 201 status code, GET should return 200.

**Comment by lsilva-kununu** [comment]
Reduce some controller complexity, great for controller testing. :-D

**Comment by lsilva-kununu** [comment]
What do you think? :)

**Comment by cojack** [comment]
@lsilva-kununu it's not good approach to remove status codes at all, because post doesn't have to return 201 all the time. You can also do a POST|PUT|PATCH /resource/id to UPDATE the entity, and this will return 200, POST /resource/subresource can also return 204 as NO CONTENT, GET might return 202 as ACCEPTED.
But I totally agree that controllers should be able to return a promise from method and nest should respond to the ether with resolved value from promise && status 200 with content type suitable to the requested.

**Comment by lsilva-kununu** [comment]
@cojack to solve the first problem, you can use annotations for status code if you want, if not, nest should follow rest patterns.

**Comment by 19majkel94** [comment]
@lsilva-kununu If you like it, try [routing-controllers](https://github.com/pleerock/routing-controllers). You return a value from action there and it's automatically wrapped into response.

**Comment by luqezman** [comment]
@19majkel94 I love this way. Is better and avoid a lot of mock in controller tests.

**Comment by luqezman** [comment]
@cojack watch https://github.com/pleerock/routing-controllers. Very usefull

**Comment by kamilmysliwiec** [comment]
Hi @luqezman,
It's possible since the v4 release. Now, you can return plain value, promise and even `Observable`. Hope you'll enjoy!  http://www.docs.nestjs.com/controllers
Thanks, Kamil

**Comment by luqezman** [comment]
@kamilmysliwiec Love you again <3
