### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by alex-chuev** [kamilmysliwiec/nest#149]
The site with the documentation stopped working.

http://docs.nestjs.com

**Comment by kattsushi** [comment]
+1

**Comment by cojack** [comment]
@alex-chuev @kattsushi use this one for now  https://kamilmysliwiec.gitbooks.io/nest/content

**Comment by zxsoft** [comment]
Why don't the author put a index.html on docs.nestjs.com and redirect to the working address

**Comment by cojack** [comment]
@zxsoft because docs are now under heavy development and stay tune :+1:

**Comment by alex-chuev** [comment]
Now it is clear. So the cats were the cause of the problem with the documentation... :smile:

**Comment by kamilmysliwiec** [comment]
well, that's it @alex-chuev :smile: enjoy v4!

**Comment by Rejpal** [comment]
Documentation page https://docs.nestjs.com/controllers
have the navigation bar cut off in the middle 
![Screenshot from 2019-08-14 14-37-06](https://user-images.githubusercontent.com/16257294/63021526-11411200-bea1-11e9-858d-4d58f2138a13.png)

it is caused by attribute `max-height: 350px;` 
![Screenshot from 2019-08-14 14-39-14](https://user-images.githubusercontent.com/16257294/63021642-582f0780-bea1-11e9-9427-d10f563a2f55.png)

when you disable it it works as expected

![Screenshot from 2019-08-14 14-40-05](https://user-images.githubusercontent.com/16257294/63021689-709f2200-bea1-11e9-9815-24ab70e1a54d.png)
