### ISSUE TITLE
Co-operation with pleerock/routing-controllers project

### ISSUE THREAD

**Issue by NoNameProvided** [kamilmysliwiec/nest#24]
I am not the author just a happy user of [pleerock/routing-controllers](https://github.com/pleerock/routing-controllers) but it's clearly visible both project want to solve the same goal. Wouldn't it make sense to co-operate the efforts?

cc @pleerock to see what does he think

**Comment by kamilmysliwiec** [comment]
Hi @NoNameProvided,
Thank you for your suggestion. Routing-controllers is an amazing library, just like the rest of @pleerock projects, e.g. @typeorm, but I think both Nest and routing-controllers have different use cases. Of course, the controllers syntax is really similar and naming convention is comparable, but it's everything. At the background is hidden completely different ecosystem, so it is too late to change it. I suppose that @pleerock has the same opinion ;)

**Comment by NoNameProvided** [comment]
Would you mind explaining me the differences you think prevent merging this two in the long term? 

At usage level they are the same, using decorators to enable a declarative way of creating Express (+ Koa ) applications. This same goal which is the the strong reason to co-operate, even if now things works quite different under the hood. In the long term both project will start solve redundant problems which has been already solved in the other.

**Comment by pleerock** [comment]
@NoNameProvided routing-controllers and nest purposes are different - routing-controllers is just a routing library, while nest is a complete framework. I don't think its reasonable for nest author to merge both projects because it may become a pain then to deal with design choices / other issues related to routing part of the application if he choose to use routing-controllers. Its more flexible for @kamilmysliwiec to develop its own components with nest-specific features and requirements. BTW love nest library logo, looks really really stylish 💯

**Comment by olee** [comment]
I searched around a lot, but didn't find any good comparison of nestjs and routing-controllers and even after reading a lot of the guides, I cant really find any big difference.
Could one of you maybe clarify this a bit?
Because currently I'm using routing-controllers because I found that one first and now I'm wondering, if I should use nestjs instead (as I just started writing the application and it would be really simple to switch as those two are quite similar).

**Comment by NoNameProvided** [comment]
NestJS is much more like a framework, it's more opinionated how things should be done. Routing-controllers gives you the tools but how you build your app is up to you. Both has its pros and cons.

**Comment by olee** [comment]
That's the thing - I don't see where NestJS is more of a framework than routing-controllers.
I don't see much of a feature NestJS has that routing-controllers does not have (except some **optional** addons like GraphQL etc.)

**Comment by NoNameProvided** [comment]
NestJS is designed after Angular, it has opinion on how you should 
 - organize your code, 
 - inject code, 
 - test your code 

You can do it other ways as well, but you shoulnd't. Routing-controllers doesn't tell you how to do them, you can use whatever you want.

**Comment by olee** [comment]
Ah so basically the DI is one of the biggest differences. That makes sense.
Thanks for the info!
