### ISSUE TITLE
How pass params to the Middleware?

### ISSUE THREAD

**Issue by cdiaz** [kamilmysliwiec/nest#3]
Congratulations, it's a cool framework.

I'm need restrict access to route on role-based.
This works for me on express:

```
app.get('/params', middleware.hasRole(['admin', 'creator', 'editor']), function(req,res){});
```
I have tried to implement a NestMiddleware, but I can not pass the parameters to it:

```
builder.use({
    middlewares: [ HasRole ],
    forRoutes: [{
    	path: 'dashboard', 
    	method: RequestMethod.ALL, 
    	data: { 'roles': ['admin', 'creator', 'editor'] } 
    }]
})
```

Here we can think of implementing guardians directly in the controller, inspired by the canActivate concept of Angular2:

```
{
  path: 'dashboard', 
  component: dashboardComponent, 
  canActivate: [ RoleGuard ], 
  data: { roles: [ 'admin', 'creator', 'editor' ] } 
}
```

Something like so:
```
@RequestMapping({ 
	path: '/dashboard', 
	method: RequestMethod.GET, 
	canActivate: [ HasRole ],
	data: { roles: [ 'admin', 'creator', 'editor' ] } 
})
```

@kamilmysliwiec What do you think is better, do you plan to implement something like this for the future?

**Comment by kamilmysliwiec** [comment]
Hi @cdiaz,

Thanks! :) It is a good question. Since Middlewares in Nest are just types it is not so easy to pass them additional data. I have been wondering how to provide this feature in easy way to use and I decided to do it as below:

```
builder.use(HasRole)
    .with(['admin', 'creator', 'editor'])
    .forRoutes({
        path: 'dashboard',
        method: RequestMethod.ALL
    });
```
So it will be still possible to chain `use()` calls, pass arrays in both `use()` and `forRoutes()` and also add some custom data between `use()` and `forRoutes()` calls (`with()` - of course - is optional). Is it looks more intuitive? What do you think? 

Referring to your proposal with `canActivate` concept - some middlewares just decorate requests with data. Their responsibility is not only to activate / deactivate routes. This is why I drop this idea :)

**Comment by kamilmysliwiec** [comment]
So finally:

Since **RC.8** - `use()` method is deprecated.
Instead of `use()` method you should use `apply()`.

**Old way (deprecated):**
```
builder.use({
    middlewares: [ HasRole ],
    forRoutes: [{
    	path: 'dashboard', 
    	method: RequestMethod.ALL, 
    	data: { 'roles': ['admin', 'creator', 'editor'] } 
    }]
})
```

**New way:**
```
builder.apply(HasRole)
    .with('admin', 'creator', 'editor')
    .forRoutes({
        path: 'dashboard',
        method: RequestMethod.ALL
    });
```

Using `with()` you can pass whatever you want (objects, arrays etc.) to the middleware `resolve(...args)` method. You only have to separate arguments by comma.

Now, your `resolve()` method of `HasRole` middleware should looks like that:

```
class HasRole {
    resolve(...roles) {
        /// the rest
    }
}
```

Where `roles` is an array of arguments passed by `with()` method (in this example, I used spread operator).

**Comment by cdiaz** [comment]
This is great and very useful, just what I wanted.
Thanks

**Comment by nextsoftpl** [comment]
That's really nice, however how can i inject a service then in the middleware? when passing parameters to resolve, then injection stops working
