### ISSUE TITLE
Singletons

### ISSUE THREAD

**Issue by zachgrayio** [kamilmysliwiec/nest#47]
What's the preferred method for defining a singleton? 

An `@Singleton` decorator might be nice.

**Comment by JulianBiermann** [comment]
Currently you can use the factory injection to create singleton objects.

```typescript
@Module({
  components: [
    SingletonClass,
    {
      provide: 'SingletonClass',
      useFactory: (singletonClass: SingletonClass) => {
        return singletonClass.getInstance();
      },
    }
  ],
})
export class ModelsModule {
}
```

**Comment by kamilmysliwiec** [comment]
Hi @zachgrayio,

All components are **singletons** across the module. If you want to have a singleton across entire application, you can use something like [shared module](https://kamilmysliwiec.gitbooks.io/nest/content/advanced/shared-module.html).

@JulianBiermann - same here, you do not have to use a factory.

**Comment by artaommahe** [comment]
@kamilmysliwiec look at image from your link with shared modules, if UserService from User module will be used in other modules than it should be in shared module (whats wrong cause it's User module related thing) or modules structure should be very complex and non-obvious.
What is use-case for making services only module-scoped singletons and not application wide? As i remember angular team moved from module to app scoped services. IMHO app singletons is more common use-case.

**Comment by kamilmysliwiec** [comment]
@artaommahe idea was changed since last update. Components are still **singletons** across the module, but modules are **not singletons** across the entire application. It means that you can easily reuse modules in different parts of application and - using hierarchical injector powers - provide them different context. This solution helps with e.g. CQRS module and should help with a lot of 3rd party modules, which will be created in the future.

However, you can still share each module using `@Shared()` decorator. Also - it is possible to share one module between 2-3..* modules in chosen namespace, e.g. `@Shared('namespace')`. If you want to share 3rd party module, just use `Shared()(ModuleName`)`.

About your example - why you want to place `UserService` in `SharedModule`? `UserService` is a part of `UserModule` context, so it should be located in the `UserModule`. If `UserService` has to be used in other modules, just **export** it and **import** `UserModule`. If `UserService` should be available and also - has to be a singleton - just mark module as a `@Shared()` and you will have single instance across entire application.

**Comment by artaommahe** [comment]
> If UserService has to be used in other modules, just export it and import UserModule
cause it can have storage (memory storage with users e.x.) and so this service should be same for all consumers

Missed that `@Shared` releases, thx

**Comment by kamilmysliwiec** [comment]
@artaommahe, it is my mistake - documentation should be updated as soon as possible :)

**Comment by totalard** [comment]
cant access the resource located in Gitbook.com.. Kindly Fix, or post the answer in the github issue. or any link please

**Comment by malavshah9** [comment]
> cant access the resource located in Gitbook.com.. Kindly Fix, or post the answer in the github issue. or any link please

same here
