### ISSUE TITLE
Validation/Filtering layer.

### ISSUE THREAD

**Issue by lsilva-kununu** [kamilmysliwiec/nest#69]
How would you guys go about to validation/filtering layer?

**Comment by JulianBiermann** [comment]
1. Create middleware which is applied to a controller

or

2. Check parameters, body content etc. in the controller itself.

Using middleware you can keep your controllers clean from validation logic.

I prefer the first method

**Comment by lsilva-kununu** [comment]
Would be nice to have validations out of the box :)

**Comment by battila7** [comment]
I don't think validation should be an out-of-the-box feature, because of two reasons:

1. It's hard to create an implementation that fits all needs.
1. Middlewares are easy to implement and provide more flexibility.

As @JulianBiermann  said, you should create a middleware with the necessary validation logic.

For this purpose, [Joi ](https://github.com/hapijs/joi )can be borrowed from Express :smile:

I think you can even develop a decorator for routes that can take a Joi object and apply it to the payload. However that might be a bit of overengineering, depending on your needs.

**Comment by 19majkel94** [comment]
> I don't think validation should be an out-of-the-box feature, because of two reasons:
It's hard to create an implementation that fits all needs.

Here you go 😉 
https://github.com/pleerock/routing-controllers#auto-validating-action-params

**Comment by battila7** [comment]
@19majkel94 
Sure, it looks great, but it's still one specific way to approach the problem. Others might prefer decoratorless implementations or whatever.

I'm not saying that there's no good solution at all. I'm trying to point out the fact that this is a higher-level problem (with great existing solutions) which should not be implemented at framework level so that clients must make use of that implementation, but a foundation should be provided for third-party solutions (just like the one you've linked).

**Comment by 19majkel94** [comment]
> which should not be implemented at framework level 

Auto-validation action params ( like `@Body`) is a greate feature, it's reducing boilerplate of calling `validate` manually each time. It could even be generic - support other validating libraries with a config function which receive the param object and call `validate` or other function from the lib.

**Comment by kamilmysliwiec** [comment]
Hi guys,
I agree with both @battila7 and @19majkel94. In my opinion auto-validation logic implemented at a framework level is not a good idea - this is why it isn't provided out-of-the-box. The validation logic always depends on a lot of factors and the main idea of Nest is to give as much flexibility as possible. However, in a lot of cases - auto-validation of actions params (just as @19majkel94 mentioned - `@Body()`, `@Param()` etc) is helpful and reduce boilerplate code in middlewares / controllers. Also - middleware does not have an access to metatypes of the properties, so it is not so easy to create a generic solution.

I have a concept, which should makes much easier validation / mapping stuff and it should be available in the nearest future. Stay tuned :cat:

**Comment by kamilmysliwiec** [comment]
Hi guys!
Since `3.0.0` pipes feature is available. You can use it for validation / transformation purposes :) [Read more](https://docs.nestjs.com/quick-start/pipes.html)

**Comment by luqezman** [comment]
@kamilmysliwiec <3
